name: Run Python Script Every 3 Hours

on:
  schedule:
    - cron: "0 */3 * * *"  # F체hrt den Workflow alle 3 Stunden aus

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4  # Verwende die neueste Version von checkout

    - name: Set up Python
      uses: actions/setup-python@v4  # Neueste Version von setup-python verwenden
      with:
        python-version: '3.10'  # W채hle die gew체nschte Python-Version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the script
      run: |
        python dein_script.py  # Ersetze 'dein_script.py' durch den tats채chlichen Namen deines Skripts
